### ISSUE TITLE
Advancing in Javascript

### ISSUE THREAD

**Issue by baweaver** [raganwald/AMA#1]
What would you say are the most important concepts to learn in the pursuit of becoming a javascript expert?

**Comment by raganwald** [comment]
To be perfectly candid, I am not a JavaScript expert. Mostly what I do is write about general-purpose programming ideas that are expressed in JavaScript, because that’s the language that hits a sweet spot of being popular enough that people will understand the ideas, and powerful enough that I don’t need to do extreme backflips to get the ideas to work.

**Comment by raganwald** [comment]
There are some good resources for online learning. [Eric Elliott](http://ericelliottjs.com) has a great list here on GitHub:

https://github.com/ericelliott/essential-javascript-links

The books on there are all excellent.

**Comment by codylindley** [comment]
I just compiled a list for learning JS. It might be of benefit. If not ignore it. http://frontenddeveloperjob.com/learn-javascript/

**Comment by raganwald** [comment]
Good list, thank you @codylindley.

**Comment by CrossEye** [comment]
> Eric Elliott has a great list here on GitHub:
> https://github.com/ericelliott/essential-javascript-links

The books are excellent.  The online resources are good too, but perhaps a little skewed towards Eric Elliot's own work, and his particular point of view.  There's plenty of good to be said about that viewpoint, but this list makes it sound as though the controversial arguments he makes are well settled in the community.

**Comment by raganwald** [comment]
> There's plenty of good to be said about that viewpoint, but this list makes it sound as though the controversial arguments he makes are well settled in the community.

I think the fashionable word for this is that it’s an _opinionated_ list. I try to be opinionated as well. I guess you are saying that the list is opinionated without disclosing that it is opinionated. In that case, it’s excellent that you’re mentioning this so that others may realize it’s important to look at a variety of sources.

**Comment by baweaver** [comment]
I was really a fan of Functional Javascript: http://www.amazon.com/Functional-JavaScript-Introducing-Programming-Underscore-js/dp/1449360726

I still kinda wish some of your books were available in print edition.

**Comment by CrossEye** [comment]
@raganwald:  Words keep disappearing for hours or days.  Yes, that's precisely the word I was looking for.  I like opinionated writing, but I do feel a list like this should disclose the fact a little better.

**Comment by raganwald** [comment]
I explicitly licensed most of my books so that readers could make print editions and sell them if they want. Why not take a crack at it?
